spring.application.name=inventarios

# Agregamos allowPublicKeyRetrieval=true al final de la URL
spring.datasource.url=jdbc:mysql://localhost:3306/inventarios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=75387414
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto actualizado para Hibernate 6 (evita el ClassNotFoundException)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
